version: 2

models:

- name: base_shopify_orders
  description: >
    Shopify API docs [here](https://help.shopify.com/api/reference/order).
  columns:
  - name: order_id
    tests:
    - not_null
    - unique
  - name: customer_id
    tests:
    - relationships:
        field: customer_id
        to: ref('stg_shopify_customers')
  - name: total_price
    description: >
      total_line_items_price + discounts + shipping + (when currency = USD) tax
  - name: total_price_usd
    description: >
      total_price converted from currency value to USD. Note: this is the ONLY
      revenue component that is converted (tax, discount, shipping are all still
      in local currency)
    
- name: stg_shopify_checkouts
  description: >
    Shopify API docs [here](https://help.shopify.com/en/api/reference/orders/abandoned-checkouts).
  columns:
  - name: checkout_id
    tests:
    - not_null
    - unique
  - name: customer_id
    tests:
    - relationships:
        field: customer_id
        to: ref('stg_shopify_customers')
    
- name: stg_shopify_customers
  description: >
    Shopify API docs [here](https://help.shopify.com/en/api/reference/customers/customer).
  columns:
  - name: customer_id
    tests:
    - not_null
    - unique
    
- name: stg_shopify_discount_codes
  description: >
    Shopify API docs [here](https://help.shopify.com/en/api/reference/discounts).
  columns:
  - name: order_id
    tests:
    - not_null
    - unique
    - relationships:
        field: order_id
        to: ref('base_shopify_orders')
        
- name: stg_shopify_transactions
  description: >
    Shopify API docs [here](https://help.shopify.com/en/api/reference/orders/transaction).
  columns:
  - name: transaction_id
    tests:
    - not_null
    - unique
  - name: order_id
    tests:
    - not_null
    - relationships:
        field: order_id
        to: ref('base_shopify_orders')
        
- name: stg_shopify_refunds
  description: >
    Shopify API docs [here](https://help.shopify.com/en/api/reference/orders/refund).
    We use the json `refund` field from the `orders` table instead of using the 
    `order_refunds` table simply because the `order_refunds` table in Stitch syncs 
    slowly. This reduces the number of tables we need to select from and it provides
    all of the desired attributes.
  columns:
  - name: refund_id
    tests:
    - not_null
    - unique
  - name: order_id
    tests:
    - not_null
    - relationships:
        field: order_id
        to: ref('base_shopify_orders')
        
- name: stg_shopify_products
  description: >
    Shopify API docs [here](https://help.shopify.com/en/api/reference/products/product).
  columns:
  - name: product_id
    tests:
    - not_null
    - unique

- name: stg_shopify_product_variants
  description: >
    Shopify API docs [here](https://help.shopify.com/en/api/reference/products/product-variant).
  columns:
  - name: variant_id
    tests:
    - not_null
    - unique
    
- name: stg_shopify_order_items
  description: >
    Shopify API docs [here](https://help.shopify.com/api/reference/order).
  columns:
  - name: order_item_id
    tests:
    - not_null
    - unique
  - name: order_id
    tests:
    - not_null
    - relationships:
        field: order_id
        to: ref('base_shopify_orders')
  - name: product_id
    tests:
    - relationships:
        field: product_id
        to: ref('stg_shopify_products')
